##Networked *Ulysses*


Networked *Ulysses* is based on the assumption that, just like it takes a village to raise a child, it takes a network of agents/actants to write a novel. Hence this project will explore Joyce's connection to his contemporary social world. The installation treats *Ulysses* as a networked novel and reads it through the metaphors of network culture and social media. Hence Networked *Ulysses* aims to arrive at a visualization that de-centres the authorial figure and highlights the role of Joyce's resources and collaborators. The goal is to let visitors explore some of the connections of the *Ulysses* network in order to gain an understanding of the relational character of novelistic production. This will enable readings of the division of labour in the literary field in general, and with respect to *Ulysses* in particular, that differ markedly from descriptions of the novel as the work of a single creative genius.

It will be essential for the project to gather the identities and historical physical addresses of agents/actants in order to map them. This primary stage of research will make use of the various biographical writings on Joyce as well as published collections of his letters. This includes, but is not limited to, Richard Ellmann's famous biography on Joyce, Peter Hartshorn's *James Joyce and Trieste*, and Corinna del Greco Lobner's *James Joyce's Italian Connection*. Some of Joyce's letters are collected in *Letters I-III*, edited by Stuart Gilbert, and *Selected Letters of James Joyce*, edited by Richard Ellmann. William S. Brockman's essay “Letters” will help in sifting through the many volumes of Joyce's correspondence. It would be ideal to have scans of the responses  (postcards, letters) that led Joyce to include certain facts/descriptions in the novel. These scans would also have to be transcribed for improved readability. Based on its user-friendly characteristics and intuitive appeal to a large group of viewers who are probably familiar with it, [Google Maps](http://maps.google.com) seems to be best choice for mapping (parts of) the *Ulysses* network. The application's functions are well suited for the presentation of this kind of network and might allow for the installation's afterlife as a crowd-sourcing project that gradually extends the number of connections through contributions by other researchers.      

What the project cannot achieve is a representation of the entire *Ulysses* network with all its agents/actants. In fact, the initial title The *Ulysses* Network was rejected because of its misleading insinuation that the presentation of the network could in some way be conclusive. In order to limit a possibly limitless gaze, then, the exhibit will indicate the extension of the Long Now in which Joyce's work took shape by choosing a small number of physical addresses for each European city involved.

The project aims at the generation of a website that is part of the exhibit The Long Now of *Ulysses*, but independent of technical constraints in the exhibit space. It shares its web presence with two other geospatial projects: one mapping *Ulysses*'s afterlife, the other displaying historical maps of Dublin. A user will be able to navigate to the different projects via a central page. Networked *Ulysses* will feature three layers in [Google Maps](http://maps.google.com), with each layer corresponding to one of the three places of composition indicated by Joyce's final entry in the novel: “Trieste – Zurich – Paris. 1914-1922.” So there will be a Trieste network, a Zurich network, and a Paris network, each taking up Joyce's presence in the respective city and mapping his contacts across Europe at the time.   

The initial idea for this project was to articulate the voices of agents/actants by letting the correspondence, in particular the responses by Joyce's correspondents, speak for itself. The feasibility of this approach, however, is questionable. The volumes of collected letters focus on Joyce, the author, and generally do not include the responses. More comprehensive research might be able to unearth some of the responses; but it is an open question to what degree such research can be done in three months. Another related potential risk is the project's scope; here some choices need to be made with respect to the following question: what agents/actants (human or non-human) should be counted as part of the three networks displayed?    
      
This difficulty of unearthing original responses indicates how Networked *Ulysses* goes against the grain of Joyce/*Ulysses* scholarship, which, by and large, has been more interested in the author than in his respondents. The field could therefore benefit from such a reversal of the angle, as it refuses to treat the novel as a monolith and provides an archeology of its production instead. More generally, this deconstructive approach has consequences for an understanding of the function of the author, in particular in the case of encyclopedic novels such as *Ulysses*. 

#Timeline
April 16th: Deliver a tested, working site/integrate with other mapping projects
March 25th: Finish revisions to site for second test
March 12: Finish third network/first test
March 4th: Finish second network in Google Maps
Feb 25th: Finish first network in Google Maps to prototype
Feb 18th: Have a list of agents/actants including biographies and contributions (scans of images/transcriptions) for one of the three networks 

In order to create the required maps, it would be helpful to have a tutorial/workshop on Java Script, in particular on the use of Google Maps APIs such as [Styled Maps](https://developers.google.com/maps/documentation/javascript/styling). In order for the final maps to be presented online and linked to a central page, we will presumably need web space.   

Using [Google Maps](http://maps.google.com) to map the connections between agents/actants in the three *Ulysses* networks (contributors, correspondents, libraries, etc.) across Europe, the installation will present an interactive display (granting visitors a degree of agency in manipulating the maps) in the form of a website including pertinent statistics (distance between actants; time and space a piece of information traveled, etc.) In analogy to current social media, the actants of the *Ulysses* network will be treated as "friends," with links and interconnections between them. Each correspondent will have an entry in [Google Maps](http://maps.google.com) as a place, linking it to the original physical address and providing a description of the agent/actant as well as an image (indicating the correspondent's contribution, ideally in the form of a scanned image and transcribed text).    

First, in terms of research, I am interested in Donna Haraway's ecofeminist criticism and Bruno Latour's Actor-Network Theory (ANT). I will therefore treat this digital project as a way of assessing the explanatory power of these theoretical approaches by applying them to a specific example. With respect to Haraway's critique of the power relations implied by a politics of representation, Networked *Ulysses* might function as a way of testing whether social media/network tools can help with the development of what Haraway calls "a politics of *articulation*." With respect to ANT, realizing Networked *Ulysses* will help in understanding what it means to say that, e.g., non-human entities like the Italian language have to be considered an actant in the *Ulysses* network. 
Secondly, in terms of teaching, which will form a large part of my future career as an instructor in post-secondary education, I hope to learn some fundamental skills in geotemporal mapping. Articulating a text's topography is *the* analytical activity par excellence. Mapping, then, becomes a fundamental analytical tool and a great skill in the preparation of pedagogical material, e.g. to illustrate the structural principles of a text in time and space, deconstruct the network behind the author-function, map the geospatial characteristics of a novel, etc.    
